//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOReserva.Models.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBReserva : DbContext
    {
        public DBReserva()
            : base("name=DBReserva")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> intento(Nullable<int> origen, Nullable<int> destino, Nullable<System.DateTime> fechita)
        {
            var origenParameter = origen.HasValue ?
                new ObjectParameter("origen", origen) :
                new ObjectParameter("origen", typeof(int));
    
            var destinoParameter = destino.HasValue ?
                new ObjectParameter("destino", destino) :
                new ObjectParameter("destino", typeof(int));
    
            var fechitaParameter = fechita.HasValue ?
                new ObjectParameter("fechita", fechita) :
                new ObjectParameter("fechita", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("intento", origenParameter, destinoParameter, fechitaParameter);
        }
    
        public virtual ObjectResult<M12_ConsultarUsuario_Result> M12_ConsultarUsuario(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M12_ConsultarUsuario_Result>("M12_ConsultarUsuario", correoParameter);
        }
    
        public virtual int M12_CrearUsuario(string nombre, string apellido, string correo, string contraseña, Nullable<int> rol, Nullable<System.DateTime> fecha, string activo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var rolParameter = rol.HasValue ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var activoParameter = activo != null ?
                new ObjectParameter("activo", activo) :
                new ObjectParameter("activo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("M12_CrearUsuario", nombreParameter, apellidoParameter, correoParameter, contraseñaParameter, rolParameter, fechaParameter, activoParameter);
        }
    
        public virtual int M12_EliminarUsuario(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("M12_EliminarUsuario", idParameter);
        }
    
        public virtual ObjectResult<M12_ListarUsuarios_Result> M12_ListarUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M12_ListarUsuarios_Result>("M12_ListarUsuarios");
        }
    
        public virtual int M12_ModificarUsuario(string nombre, string apellido, string correo, string contraseña, Nullable<int> rol, Nullable<int> id)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var rolParameter = rol.HasValue ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("M12_ModificarUsuario", nombreParameter, apellidoParameter, correoParameter, contraseñaParameter, rolParameter, idParameter);
        }
    
        public virtual ObjectResult<M20_ActualizarEstadoReservaHabitacion_Result> M20_ActualizarEstadoReservaHabitacion(Nullable<int> id_reserva, Nullable<int> estado)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M20_ActualizarEstadoReservaHabitacion_Result>("M20_ActualizarEstadoReservaHabitacion", id_reservaParameter, estadoParameter);
        }
    
        public virtual ObjectResult<M20_DetalleReservaHabitacion_Result> M20_DetalleReservaHabitacion(Nullable<int> id_reserva)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M20_DetalleReservaHabitacion_Result>("M20_DetalleReservaHabitacion", id_reservaParameter);
        }
    
        public virtual ObjectResult<M20_GuardarReservaHabitacion_Result> M20_GuardarReservaHabitacion(Nullable<int> id_reserva, Nullable<int> habitacion, Nullable<int> cantidad_dias, Nullable<System.DateTime> fecha_reservada, Nullable<int> hot_id, Nullable<int> usu_id, Nullable<int> estado)
        {
            var id_reservaParameter = id_reserva.HasValue ?
                new ObjectParameter("id_reserva", id_reserva) :
                new ObjectParameter("id_reserva", typeof(int));
    
            var habitacionParameter = habitacion.HasValue ?
                new ObjectParameter("habitacion", habitacion) :
                new ObjectParameter("habitacion", typeof(int));
    
            var cantidad_diasParameter = cantidad_dias.HasValue ?
                new ObjectParameter("cantidad_dias", cantidad_dias) :
                new ObjectParameter("cantidad_dias", typeof(int));
    
            var fecha_reservadaParameter = fecha_reservada.HasValue ?
                new ObjectParameter("fecha_reservada", fecha_reservada) :
                new ObjectParameter("fecha_reservada", typeof(System.DateTime));
    
            var hot_idParameter = hot_id.HasValue ?
                new ObjectParameter("hot_id", hot_id) :
                new ObjectParameter("hot_id", typeof(int));
    
            var usu_idParameter = usu_id.HasValue ?
                new ObjectParameter("usu_id", usu_id) :
                new ObjectParameter("usu_id", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M20_GuardarReservaHabitacion_Result>("M20_GuardarReservaHabitacion", id_reservaParameter, habitacionParameter, cantidad_diasParameter, fecha_reservadaParameter, hot_idParameter, usu_idParameter, estadoParameter);
        }
    
        public virtual ObjectResult<M20_HotelHistorialReservaHabitacion_Result> M20_HotelHistorialReservaHabitacion(Nullable<int> id_hotel)
        {
            var id_hotelParameter = id_hotel.HasValue ?
                new ObjectParameter("id_hotel", id_hotel) :
                new ObjectParameter("id_hotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M20_HotelHistorialReservaHabitacion_Result>("M20_HotelHistorialReservaHabitacion", id_hotelParameter);
        }
    
        public virtual ObjectResult<M20_UsuarioHistorialReservaHabitacion_Result> M20_UsuarioHistorialReservaHabitacion(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<M20_UsuarioHistorialReservaHabitacion_Result>("M20_UsuarioHistorialReservaHabitacion", id_usuarioParameter);
        }
    }
}
